spring:
  application:
    name: orchestrator-service
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: ru.aston.orchestrator
server:
  port: 8085