spring:
  application:
    name: order-service
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: ru.aston.order
  datasource:
    url: jdbc:postgresql://localhost:5432/temporal-db?currentSchema=order_service
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090